# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-26 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(default='foodsearch/images/no-img.jpg', upload_to='foodsearch/images/'),
        ),
    ]
