# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-27 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsearch', '0003_auto_20190226_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='shortdesc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
